import type { ContenidoSitio, ImagenProceso, Obra } from './tipos';

export const obrasMock: Obra[] = [
  {
    id: 'umbral',
    titulo: 'Umbral',
    tecnica: 'Óleo sobre lienzo',
    anio: 2024,
    dimensiones: '80 x 100 cm',
    descripcion:
      'Un estudio de luz y sombra en el momento exacto en que el día cede paso a la noche.',
    imagenUrl: 'linear-gradient(135deg,#8a3b2e,#d9803f 45%,#f2c14e)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(135deg,#2a1410,#5c2a1f 45%,#8a3b2e)',
    tamanoGrilla: 'normal',
    orden: 1,
  },
  {
    id: 'silencio-ocre',
    titulo: 'Silencio Ocre',
    tecnica: 'Técnica mixta',
    anio: 2023,
    dimensiones: '60 x 80 cm',
    descripcion: 'Capas de tierra y pigmento sobre una superficie que se resiste a quedar quieta.',
    imagenUrl: 'linear-gradient(150deg,#3a3226,#7a6b4f 55%,#c9b98a)',
    tieneHover: false,
    imagenHoverUrl: null,
    tamanoGrilla: 'normal',
    orden: 2,
  },
  {
    id: 'deriva',
    titulo: 'Deriva',
    tecnica: 'Óleo sobre lienzo',
    anio: 2025,
    dimensiones: '100 x 100 cm',
    descripcion: 'Una figura que se aleja de la orilla sin apuro, como quien sabe que va a volver.',
    imagenUrl: 'linear-gradient(160deg,#1f3b3a,#3d6b63 50%,#9cc0a8)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(160deg,#0a1a19,#1f3b3a 50%,#3d6b63)',
    tamanoGrilla: 'normal',
    orden: 3,
  },
  {
    id: 'horizonte-partido',
    titulo: 'Horizonte Partido',
    tecnica: 'Óleo sobre lienzo',
    anio: 2024,
    dimensiones: '220 x 70 cm',
    descripcion:
      'La cordillera vista desde el llano, pintada durante tres tardes seguidas en el mismo lugar exacto.',
    imagenUrl: 'linear-gradient(100deg,#1a2a4a 0%,#4a6a8a 35%,#c9a876 60%,#e8d9a8 100%)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(100deg,#0a1524 0%,#1a2a4a 35%,#6a5236 60%,#a8946a 100%)',
    tamanoGrilla: 'banner',
    orden: 4,
  },
  {
    id: 'vestigio',
    titulo: 'Vestigio',
    tecnica: 'Acrílico',
    anio: 2024,
    dimensiones: '40 x 50 cm',
    descripcion: 'Lo que queda de una casa cuando ya no vive nadie adentro.',
    imagenUrl: 'linear-gradient(140deg,#4a1f2b,#8c3b4a 50%,#d98a7a)',
    tieneHover: false,
    imagenHoverUrl: null,
    tamanoGrilla: 'chica',
    orden: 5,
  },
  {
    id: 'ceniza-y-luz',
    titulo: 'Ceniza y Luz',
    tecnica: 'Técnica mixta',
    anio: 2022,
    dimensiones: '45 x 55 cm',
    descripcion: 'Pintada después del incendio, con el humo todavía metido en la ropa.',
    imagenUrl: 'linear-gradient(155deg,#21201d,#55524a 55%,#a89f8c)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(155deg,#0c0b09,#21201d 55%,#55524a)',
    tamanoGrilla: 'chica',
    orden: 6,
  },
  {
    id: 'marea',
    titulo: 'Marea',
    tecnica: 'Óleo sobre lienzo',
    anio: 2025,
    dimensiones: '50 x 60 cm',
    descripcion: 'El mar visto desde muy adentro tierra, de memoria, no del natural.',
    imagenUrl: 'linear-gradient(145deg,#142838,#2f5470 50%,#9db8c9)',
    tieneHover: false,
    imagenHoverUrl: null,
    tamanoGrilla: 'chica',
    orden: 7,
  },
  {
    id: 'retrato-sin-nombre',
    titulo: 'Retrato sin Nombre',
    tecnica: 'Óleo sobre lienzo',
    anio: 2023,
    dimensiones: '55 x 65 cm',
    descripcion: 'Un rostro que el artista vio una sola vez y no pudo dejar de pintar.',
    imagenUrl: 'linear-gradient(165deg,#3a1c1c,#8c4a3a 50%,#e0a56a)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(165deg,#180c0c,#3a1c1c 50%,#8c4a3a)',
    tamanoGrilla: 'chica',
    orden: 8,
  },
  {
    id: 'casa-de-invierno',
    titulo: 'Casa de Invierno',
    tecnica: 'Acrílico',
    anio: 2022,
    dimensiones: '70 x 90 cm',
    descripcion: 'La luz fría de julio entrando por una ventana que da al patio de atrás.',
    imagenUrl: 'linear-gradient(130deg,#22303f,#5c7d92 50%,#c9d6d9)',
    tieneHover: false,
    imagenHoverUrl: null,
    tamanoGrilla: 'normal',
    orden: 9,
  },
  {
    id: 'cordillera-baja',
    titulo: 'Cordillera Baja',
    tecnica: 'Grafito sobre papel',
    anio: 2021,
    dimensiones: '200 x 60 cm',
    descripcion: 'Boceto de campo, hecho en una sola sentada antes de que cambiara la luz.',
    imagenUrl: 'linear-gradient(95deg,#cfcabb 0%,#a9a493 45%,#7d7768 100%)',
    tieneHover: false,
    imagenHoverUrl: null,
    tamanoGrilla: 'banner',
    orden: 10,
  },
  {
    id: 'gallo-turquesa',
    titulo: 'Gallo Turquesa',
    tecnica: 'Técnica mixta',
    anio: 2025,
    dimensiones: '48 x 58 cm',
    descripcion: 'Encargo de un vecino que quería a su gallo pintado como si fuera un santo.',
    imagenUrl: 'linear-gradient(150deg,#0d3b3d,#1c8f8a 50%,#7fe3d4)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(150deg,#031616,#0d3b3d 50%,#1c8f8a)',
    tamanoGrilla: 'chica',
    orden: 11,
  },
  {
    id: 'patio-rojo',
    titulo: 'Patio Rojo',
    tecnica: 'Óleo sobre lienzo',
    anio: 2024,
    dimensiones: '75 x 75 cm',
    descripcion: 'Los tres tonos de rojo que había en las paredes de la casa donde creció.',
    imagenUrl: 'linear-gradient(140deg,#5c1414,#a8302a 45%,#e0725a)',
    tieneHover: true,
    imagenHoverUrl: 'linear-gradient(140deg,#280808,#5c1414 45%,#a8302a)',
    tamanoGrilla: 'normal',
    orden: 12,
  },
];

export const procesoMock: ImagenProceso[] = [
  {
    id: 'proceso-1',
    imagenUrl: 'linear-gradient(160deg,#1a1410,#3d2a1f 55%,#6b4a35)',
    textoCorto: 'Boceto inicial a lápiz',
    orden: 1,
  },
  {
    id: 'proceso-2',
    imagenUrl: 'linear-gradient(150deg,#f4f1e4,#d9d2b8 60%,#a89f8c)',
    textoCorto: 'Estudio de composición',
    orden: 2,
  },
  {
    id: 'proceso-3',
    imagenUrl: 'linear-gradient(140deg,#0d2b2f,#1c5b5f 55%,#3fa8a3)',
    textoCorto: 'Primeras capas de color',
    orden: 3,
  },
  {
    id: 'proceso-4',
    imagenUrl: 'linear-gradient(130deg,#2a1a2f,#6b3a5f 55%,#c97a9a)',
    textoCorto: 'Ajuste de valores',
    orden: 4,
  },
  {
    id: 'proceso-5',
    imagenUrl: 'linear-gradient(120deg,#1f2a1a,#4a6b35 55%,#9ac97a)',
    textoCorto: 'Detalle final',
    orden: 5,
  },
  {
    id: 'proceso-6',
    imagenUrl: 'linear-gradient(110deg,#2f1f14,#7a4a2a 55%,#d9a35f)',
    textoCorto: 'Pieza terminada en el taller',
    orden: 6,
  },
];

export const contenidoSitioMock: ContenidoSitio = {
  heroTitulo: 'Salomón Barrios',
  heroSubtitulo: 'Artista Digital, pintor, ilustrador.',
  heroImagenUrl: 'linear-gradient(175deg,#3d4a5c 0%,#6b7a8a 40%,#8a9aa5 65%,#c9b896 100%)',
  declaracionTexto:
    'Vid mo quo endebitin plaut odicillam, officium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi, quo min pliquo offic te aut ea nost as net, comnia dolupta tiorestrum vidis repres et, comnist velibusdae sinum faceptios eriscid et am natem est.',
  bioTexto:
    'Vid mo quo endebitin plaut odicillam, officium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi, quo min pliquo offic te aut ea nost as net, comnia dolupta tiorestrum vidis repres et, comnist velibusdae sinum faceptios eriscid et am natem est, ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique quiberu mquiamus, omni od qui dolupta tentem dit aut et derum conet alicimi ntiatur, aborestores idunt quam et et et acerum non cusapero es as rendam, comnihil mint et istem rest a asinus exerate reprem quatem andaectus eium num labo.\n\nAqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio. Nam natior rerspitiist, simagni nihitia epelendandit dolumendam sant fuga. Et ius earumqu aecuscium, omnimag nisincia cus autatquidis nus, sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur?\n\nEhenis quas et et et fuga. Por ant, incte officiae. Nihitas expliatur rerum ex es mi, nobita qui quisque veriae eaque et quiatem quianim et eaquaec torerepudam ipient di to illam, to omnihic atquatatiis et fuga.',
  cvTexto:
    'Vid mo quo endebitin plaut odicillam, officium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi, quo min pliquo offic te aut ea nost as net, comnia dolupta tiorestrum vidis repres et, comnist velibusdae sinum faceptios eriscid et am natem est, ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique quiberu mquiamus, omni od qui dolupta tentem dit aut et derum conet alicimi ntiatur, aborestores idunt quam et et et acerum non cusapero es as rendam, comnihil mint et istem rest a asinus exerate reprem quatem andaectus eium num labo.\n\nAqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio. Nam natior rerspitiist, simagni nihitia epelendandit dolumendam sant fuga. Et ius earumqu aecuscium, omnimag nisincia cus autatquidis nus, sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur.\n\nEhenis quas et et et fuga. Por ant, incte officiae. Nihitas expliatur rerum ex es mi, nobita qui quisque veriae eaque et quiatem quianim et eaquaec torerepudam ipient di to illam, to omnihic atquatatiis et fuga, comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi quo min pliquo offic te aut ea nost as net comnia dolupta tiorestrum vidis repres et comnist velibusdae sinum faceptios eriscid.\n\nOmni od qui dolupta tentem dit aut et derum conet alicimi ntiatur aborestores idunt quam et et et acerum non cusapero es as rendam comnihil mint et istem rest a asinus exerate reprem quatem andaectus eium num labo aqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga.\n\nEt ius earumqu aecuscium omnimag nisincia cus autatquidis nus sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur.\n\nVid mo quo endebitin plaut odicillam officium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi quo min pliquo offic te aut ea nost as net comnia dolupta tiorestrum vidis repres et comnist velibusdae sinum faceptios eriscid et am natem est ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique.\n\nQuiberu mquiamus omni od qui dolupta tentem dit aut et derum conet alicimi ntiatur aborestores idunt quam et et et acerum non cusapero es as rendam comnihil mint et istem rest a asinus exerate reprem quatem andaectus eium num labo aqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga et ius earumqu aecuscium.\n\nOmnimag nisincia cus autatquidis nus sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur ehenis quas et et et fuga.\n\nPor ant incte officiae nihitas expliatur rerum ex es mi nobita qui quisque veriae eaque et quiatem quianim et eaquaec torerepudam ipient di to illam to omnihic atquatatiis et fuga comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi quo min pliquo offic te aut ea nost as net comnia dolupta tiorestrum vidis repres et.\n\nComnist velibusdae sinum faceptios eriscid et am natem est ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique quiberu mquiamus omni od qui dolupta tentem dit aut et derum conet alicimi ntiatur aborestores idunt quam et et et acerum non cusapero es as rendam comnihil mint et istem rest a asinus exerate reprem quatem.\n\nAndaectus eium num labo aqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga et ius earumqu aecuscium omnimag nisincia cus autatquidis nus sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti.\n\nAs et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur ehenis quas et et et fuga por ant incte officiae nihitas expliatur rerum ex es mi nobita qui quisque veriae.\n\nEaque et quiatem quianim et eaquaec torerepudam ipient di to illam to omnihic atquatatiis et fuga, vid mo quo endebitin plaut odicillam officium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi quo min pliquo offic te aut ea nost as net comnia dolupta tiorestrum vidis repres et.\n\nOfficium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi quo min pliquo offic te aut ea nost as net comnia dolupta tiorestrum vidis repres et comnist velibusdae sinum faceptios eriscid et am natem est ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique quiberu mquiamus.\n\nOmni od qui dolupta tentem dit aut et derum conet alicimi ntiatur aborestores idunt quam et et et acerum non cusapero es as rendam comnihil mint et istem rest a asinus exerate reprem quatem andaectus eium num labo aqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga et ius earumqu aecuscium omnimag nisincia.\n\nCus autatquidis nus sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur ehenis quas et et et fuga.\n\nPor ant incte officiae nihitas expliatur rerum ex es mi nobita qui quisque veriae eaque et quiatem quianim et eaquaec torerepudam ipient di to illam to omnihic atquatatiis et fuga, andaectus eium num labo aqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga.\n\nEt ius earumqu aecuscium omnimag nisincia cus autatquidis nus sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates.\n\nSam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur, vid mo quo endebitin plaut odicillam officium et omnit estrum rerspicia doluptae comnimil et et repeditatet as elloresto omnisitis eaquibus entia sanda quias parchil igenimi quo min pliquo offic te aut ea nost as net comnia dolupta tiorestrum vidis repres et comnist velibusdae sinum faceptios eriscid.\n\nEt am natem est ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique quiberu mquiamus omni od qui dolupta tentem dit aut et derum conet alicimi ntiatur aborestores idunt quam et et et acerum non cusapero es as rendam comnihil mint et istem rest a asinus exerate reprem quatem andaectus eium num labo.\n\nAqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga et ius earumqu aecuscium omnimag nisincia cus autatquidis nus sunt volum facearumquo explique nim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis.\n\nDolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur ehenis quas et et et fuga por ant incte officiae nihitas expliatur rerum ex es mi nobita qui quisque veriae eaque et quiatem.\n\nQuianim et eaquaec torerepudam ipient di to illam to omnihic atquatatiis et fuga, comnist velibusdae sinum faceptios eriscid et am natem est ulluptae vendaepel int et vide vid eossi dicia con et faccatus vidicit fugitio rendit quos id ullorempos alique quiberu mquiamus omni od qui dolupta tentem dit aut et derum conet alicimi ntiatur aborestores idunt quam et et et acerum.\n\nNon cusapero es as rendam comnihil mint et istem rest a asinus exerate reprem quatem, andaectus eium num labo aqui conseristi dus et endercipsus enditat quistia inusam int quia conet quo magnis conse nonEditio nam natior rerspitiist simagni nihitia epelendandit dolumendam sant fuga et ius earumqu aecuscium omnimag nisincia cus autatquidis nus sunt volum facearumquo explique.\n\nNim illabor ersped explatia sinverunt ut quae por re vollita quatemporere la doloriti as et eum latia ipsapis dolecto molupta ecuscilitiis doluptaecus doles ellorrum ditibus is remquistrum aut officie ntorporatem laceritate commoles quia cum nim quassite magni nobis doluptates sam quis aut inti suntias et quas plibearum endantium aspicat vendit qui deruptatur, ehenis quas et et et fuga.',
  contactoTelefono: '+57 319 2274010',
  contactoEmail: 'salomonbp12@gmail.com',
  instagramUrl: 'https://instagram.com',
  tiktokUrl: 'https://tiktok.com',
};
